runtime: python27
api_version: 1
threadsafe: true
service: test-backend

handlers:
- url: /.*
  script: main.app

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'humansvszombies-24348'
